package persistence.entities;

import java.sql.Timestamp;

import com.fasterxml.jackson.annotation.JsonBackReference;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.NonNull;

/**
 * The Road class represents a road segment in the system.
 * It includes details about the type of pavement, the length of the road,
 * and timestamps for when the road segment was created and last updated.
 *
 * This entity is mapped to the "ROAD" table in the database.
 */
@Data
@NoArgsConstructor
@Entity
@Table(name = "road")
public class Road {

    /**
     * The unique identifier for the road.
     * It is auto-generated by the database and is the primary key of the "ROAD" table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Integer id;

    /**
     * The segment associated with this road.
     * This represents a many-to-one relationship, where multiple roads can be associated with a single segment.
     * It is mapped to the "segment_id" column in the "ROAD" table and references the "id" column in the "Segment" table.
     */
    @ManyToOne
    @JoinColumn(name = "segment_id", referencedColumnName = "id")
    @JsonBackReference
    private Segment segment;

    /**
     * The type of pavement for the road.
     * It is stored as a string in the "pavement_type" column in the "ROAD" table.
     */
    @NonNull
    @Column(name = "pavement_type", nullable = false)
    private String pavementType;

    /**
     * The length of the road.
     * It is stored as a float in the "length" column in the "ROAD" table.
     */
    @NonNull
    @Column(name = "length", nullable = false)
    private Float length;

    /**
     * The timestamp for when the road segment was created.
     * It is stored in the "created_at" column in the "ROAD" table.
     */
    @NonNull
    @Column(name = "created_at", nullable = false)
    private Timestamp createdAt;

    /**
     * The timestamp for when the road segment was last updated.
     * It is stored in the "updated_at" column in the "ROAD" table.
     */
    @NonNull
    @Column(name = "updated_at", nullable = false)
    private Timestamp updatedAt;

}
